# Generated by Django 4.2.30 on 2026-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_grupo_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código identificador do grupo (ex: FE-001)', max_length=20, null=True, verbose_name='Código'),
        ),
    ]
